### ISSUE TITLE
Error al tratar de usar una función...

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#100]
<img width="907" alt="nollamafunciones" src="https://cloud.githubusercontent.com/assets/8825526/21294626/18213866-c520-11e6-8227-8c7f4faba1fd.png">

**Comment by fidel-ml** [comment]
Mi error. El problema es minDir...

**Comment by fidel-ml** [comment]
También sigue diciendo "variable" en lugar de "nombre"...

**Comment by rodri042** [comment]
Esto ya está arreglado
