### ISSUE TITLE
Error informado en lugar incorrecto...

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#105]
<img width="501" alt="misplacederrorengobstonesweb" src="https://cloud.githubusercontent.com/assets/8825526/21521401/57d0b974-ccdb-11e6-985b-89e02c9849d2.png">

El error está en línea 26, pero lo informa en línea 33. Adjunto también el programa que lo produce.

[LosMovimientosDelRey.txt](https://github.com/gobstones/gobstones-web/files/675520/LosMovimientosDelRey.txt)

(No me deja adjuntar gbs... Por eso lo cambié a txt. :))

**Comment by rodri042** [comment]
El intérprete nuevo arregla esto
