### ISSUE TITLE
Soportar elegir tamaño del tablero inicial

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#11]
- En `gs-board` hay que agregar algo en la UI que permita sumar filas y columnas..
- En `gs-weblang-core` hay que deshardcodear el `9,9` de la clase `Context`.
- En `gobstones-web` hay que crear el contexto con el tamaño deseado.

**Comment by faloi** [comment]
¿Queda algo por hacer de esto?

**Comment by rodri042** [comment]
Me quedó un pequeño bug el domingo, que lo cargué como story en ready. Dsp
de eso ya estaría

**Comment by faloi** [comment]
Sí, la vi. La seguimos por ahí.
