### ISSUE TITLE
Cuando cargo un proyecto el botón de "aleatoriedad" de tableros desaparece

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#117]

**Comment by rodri042** [comment]
No lo puedo reproducir :/

Podrás subir el proyecto con el que te pasa eso?

**Comment by fidel-ml** [comment]
No me deja subirlos porque no entiende el formato de archivo... (Ni siquiera .zip, aunque dice que sí).  Te lo mando por mail.

Lo que descubrí es que no es permanente: solamente cuanto selecciono todo el código (y cuando carga hace eso por defecto -- feo). Es en Firefox.
