### ISSUE TITLE
Si hay varios procedimientos primitivos juntos, los considera una única acción atómica

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#118]
Cada procedimiento primitivo es atómico, pero al finalizar un procedimiento primitivo debe verse el estado del tablero antes de pasar al siguiente. Actualmente si pongo varios procedimientos atómicos uno detrás del otro, no veo los pasos intermedios.

**Comment by rodri042** [comment]
@fidel-ml Ahí lo arreglé. Cierro el issue y cualquier cosa reabrilo.
