### ISSUE TITLE
Algunos errores de tipo no producen BOOM, sino "Error desconocido"

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#121]
Por alguna razón, cuando intento ejecutar el programa "program { Poner(Sur) }" me dice "Error desconocido". El comportamiento correcto de este programa es hacer BOOM con un mensaje que indique que esperaba un argumento de tipo Color.
¿Están haciendo algún chequeo de tipos antes de ejecutar? Si esto es así hay que cambiarlo, porque Gobstones no usa el chequeo estático de tipos antes de ejecutar...

**Comment by rodri042** [comment]
Lo cierro porque lo probé y a día de hoy esto está andando
