### ISSUE TITLE
Las operaciones del .gbt no funcionan atómicamente

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#123]
Eso. :(

**Comment by rodri042** [comment]
Podrás subir un ejemplo? Yo probé esto: https://www.youtube.com/watch?v=hSyIjCcKNU8 y anduvo :(
O ya no pasa más?

**Comment by fidel-ml** [comment]
Te mando por mail un video de la ejecución y el proyecto "Pacman", donde puse las siguientes operaciones en el .gbt:

PonerMuchas
SacarMuchas
BuscarPersonaje
BuscarEnCuadrante

Y con el siguiente código:

HacerJugadaDelPacman(Oeste)

que llama a

MoverPersonaje(pacman(), Oeste)
if(hay(pastilla())) { Sacar(pastilla()) }
HacerJugadaDelFantasma()

siendo este último

BuscarPersonaje(fantasma())
...

Lo que ves en el video es que SacarMuchas y PonerMuchas funcionan atómicamente, pero BuscarPersonaje(fantasma()) NO. Y debería...

**Comment by rodri042** [comment]
Ahí lo vi. Sí, pasaba cuando desde la biblioteca del docente llamabas a otra rutina de la biblioteca. Ya está arreglado!
