### ISSUE TITLE
El parser debería ser un bower component para que la versión offline sea posta offline

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#13]
Como `https://npmcdn.com/gs-weblang-core@0.1.4/umd/index.umd.min.js"`. Supongo que nos traerá problemas a la hora de usar algo como Electron si las dejamos.

**Comment by faloi** [comment]
¿Al final esto fue un problema?

**Comment by rodri042** [comment]
Es que ahora apunta a https://npmcdn.com/gs-weblang-core@0.4.0/umd/index.umd.js
que sin estar conectado a internet obviamente no carga

2016-08-27 14:58 GMT-03:00 Federico Aloi <notifications@github.com>:
