### ISSUE TITLE
Los procedimientos primitivos no tienen parámetros!!!!!!

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#142]

**Comment by fidel-ml** [comment]
En la biblioteca dice "procedure PonerMuchas(n,c)" pero los parámetros no aparecen en el bloque correspondiente.

**Comment by rodri042** [comment]
Debe decir `PonerMuchas__(n,c)` o `Poner_Muchas_(n,c)` pa' que blockly sepa dónde van los agujeritos
