### ISSUE TITLE
Velocidad rápida se saltea pasos y no es más rápida

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#144]
Usando el ejemplo que pasó Fidel del pacman. Estoy probando en Chrome.

[Pacman.gdb](https://github.com/gobstones/gobstones-web/files/846027/Pacman.txt)

Adjunto video que muestra la diferencia entre velocidades. Primero, con la lenta, después con la rápida. Prestar atención a los saltos que pega con la velocidad rápida:

![pacman-small](https://cloud.githubusercontent.com/assets/5421992/23971939/b158d8f4-09ae-11e7-8273-18e3bc3f5ca9.gif)

¿Es lo que se busca con las velocidades? ¿Ocultar pasos?

Además, consume el doble de recursos. Al correrlo en velocidad baja el proceso chrome de ese tab se come 12% de mi procesador, y al correrlo en velocidad rápida se come 25%.

**Comment by rodri042** [comment]
Creo que con el nuevo `gs-board` 1.8.7 esto ya no pasa.
