### ISSUE TITLE
Al cargar un segundo proyecto sin procedimientos primitivos, quedan los del anterior

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#148]

**Comment by fidel-ml** [comment]
Por ejemplo, cuando cargo un proyecto que tiene procedimientos primitivos, y después cargo otro que no tiene, me deja los procedimientos primitivos del anterior.

**Comment by faloi** [comment]
Ok, ¿sólo pasa con los procedimientos primitivos?

**Comment by fidel-ml** [comment]
En esta ocasión, sí. Pero lo puse así, porque no sé cómo está hecho el
reseteo de proyecto, y entonces da para que verifiquen bien que sea
completo (por ejemplo, las opciones de configuración, o la biblioteca del
docente).


2017-03-24 11:18 GMT-03:00 Federico Aloi <notifications@github.com>:

**Comment by faloi** [comment]
Si cargás un segundo proyecto que sí tiene procedimientos primitivos, ¿funciona? Creo que ya sabés dónde apunta esta pregunta...

**Comment by fidel-ml** [comment]
Juaz. Sí, funciona... a medias.

O sea, si cargo un 2do proyecto con procedimientos primitivos, los
reemplaza.
PERO, si tengo abierta la pestaña de procedimientos, no se cierra y no se
refresca (o sea, veo los procedimientos primitivos viejos hasta que intento
accederlos).


2017-03-24 11:29 GMT-03:00 Federico Aloi <notifications@github.com>:
