### ISSUE TITLE
URGENTE: depurar el comportamiento de la habilitación de bloque

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#149]

**Comment by fidel-ml** [comment]
No logro que en los primeros proyectos se seleccionen ni los colores ni las direcciones. Usé "Color" y "Direccion", como había dicho Alf, pero no andan. Le pregunté a Alf qué usó, pero lo dejo registrado acá.

**Comment by fidel-ml** [comment]
Ahí hablé con Alf, y resulta que es "ColorSelector" y "DireccionSelector"... :(
Ya le dije de unificar en el criterio que habíamos hablado en el mail del 7/2, y me dijo que en la semana lo mira y lo arregla con ustedes.

**Comment by rodri042** [comment]
@fidel-ml ¿Esto se solucionó con el update del sábado de blockly? Leí que en un mail dijiste que con el update desaparecieron los "Procedimientos primitivos", pero por lo que veo no es que desaparecieron sino que los pusieron dentro de la categoría "Comandos".

**Comment by fidel-ml** [comment]
Salvo que la lista vacía habilita todo (en lugar de eliminar todo...), el
resto parece funcionar.
FF

2017-04-12 0:42 GMT-03:00 Rodrigo Alfonso <notifications@github.com>:
