### ISSUE TITLE
Cuando defino una función en GobstonesJr, el código generado está vacío

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#153]
Además tampoco usa la parentización correcta, así que quizás estamos usando una versión vieja de lo que hizo Alf. Habría que primero actualizar la versión de bloques usada, y si el error persiste, ver qué pasa...

**Comment by rodri042** [comment]
Ahí actualicé blockly a la más nueva al momento

**Comment by fidel-ml** [comment]
Alf mandó que ahora es la 0.3.0.
A mí los programas que definen y usan funciones me dan problemas (o sea, no
corren, y no generan nada de código en texto). No sé si la versión 3.0 lo
habrá arreglado, pero habría que chequear.
FF

2017-04-12 1:41 GMT-03:00 Rodrigo Alfonso <notifications@github.com>:

**Comment by rodri042** [comment]
Cierro este y lo discutimos en https://github.com/Program-AR/gs-element-blockly/issues/63
