### ISSUE TITLE
Hay ParserExceptions que quedan en la consola

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#158]
En la UI se ve `Error desconocido` pero en la developer console se ve el error posta.

**Comment by rodri042** [comment]
Podrás pasar un ejemplo de con cuál?

**Comment by rodri042** [comment]
Probé con todas y solo me pasó con `bad_expression_statement`, arreglé esa y aproveché para testear las demás en https://github.com/gobstones/gs-weblang-core/pull/65
