### ISSUE TITLE
Mejoras de usabilidad

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#16]
- Como usuario me gustaría que al entrar al sitio el IDE ya se encuentre en foco para escribir código, y no tener que hacer click en él.
- Como usuario me gustaría poder correr el código con Ctrl+Enter.

https://elements.polymer-project.org/elements/iron-a11y-keys

**Comment by faloi** [comment]
+1 al Ctrl + Enter!

**Comment by rodri042** [comment]
https://elements.polymer-project.org/elements/iron-a11y-keys
