### ISSUE TITLE
Al cargar proyecto desde URL, no se ve el editor de bloques

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#160]
Para que se vea hay que, por ejemplo, cambiar el tamaño de la ventana del navegador. :open_mouth:

**Comment by rodri042** [comment]
Con el nuevo loading de https://github.com/gobstones/gobstones-web/issues/176#issuecomment-311851415 esto (al menos a mí) ya no me pasa. Cierro y cualquier cosa reabrí!
