### ISSUE TITLE
Al cargar proyecto desde URL, *a veces* ignora algunas configuraciones del JSON

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#162]
Ejemplo: en https://gobstones.github.io/gobstones-web/#/blocks?url=https://gobstones.github.io/proyectos-jr/proyectos/Cap.2/2.3.1.2.Lugar para los corners.gbp a mí no me carga el modo aleatorio pero a @fidel-ml  sí.

**Comment by rodri042** [comment]
@faloi podés ver si sigue pasando?

**Comment by faloi** [comment]
Parecería que no. Cerramos.
