### ISSUE TITLE
Revisar el foco en el interactive

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#165]
Al ejecutar este programa y tocar las flechas, no pasa nada.

```js
interactive program {
    K_ARROW_RIGHT -> { Mover(Este)  }
    K_ARROW_LEFT  -> { Mover(Oeste) }
}
```

**Comment by rodri042** [comment]
Funciooona pero tenés que darle foco haciéndo click (si es que te sirve de algo mientras tanto hasta que lo arregle)

**Comment by faloi** [comment]
Esto sigue pasando.

**Comment by rodri042** [comment]
@faloi en staging?

**Comment by faloi** [comment]
Ah no, probé en producción yo. Más razones para sistematizar el deploy...

**Comment by rodri042** [comment]
Buen, está arreglado, ahí subí a producción.
