### ISSUE TITLE
Bug al cargar proyectos

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#169]
Al cargar el proyecto https://github.com/gobstones/proyectos-jr/blob/master/Proyectos/Cap.2/2.1.1.Simulando%20repartir%20caramelos.gbp
la mitad de las veces (las veces impares) no carga los bloques.
O sea, la primera vez no carga los bloques; si lo vuelvo a abrir, carga bien; si después lo vuelvo a abrir, no los carga... Y así.

**Comment by rodri042** [comment]
Creeeeo que essto es duplicado de https://github.com/gobstones/gobstones-web/issues/160 <- Seguimos ahí!
