### ISSUE TITLE
Si el description.md es muy largo, a veces la ventana de descripción es más grande que la pantalla

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#171]
Creo que es la primera vez que lo cargo...
Además, estaría bueno que marque de manera más heavy que hay texto fuera de la pantalla (por ejemplo, que el botón aceptar se vuelva una flecha para abajo hasta que lea todo... O algo.)

**Comment by rodri042** [comment]
Porfa subite un `description.md` que lo reproduzca :)

Ojo si tiene links a imágenes, porque sí o sí hay que ponerlas en base64. Ejemplo: https://gist.githubusercontent.com/rodri042/ece71f062a14b5aa603caa391b8177fc/raw/e32721306f7053c1ed22dd28b5e72847c1a55147/description.md

**Comment by rodri042** [comment]
Seguimos en https://github.com/gobstones/gobstones-web/issues/177
