### ISSUE TITLE
Al editar un tablero y correr un programa interactivo, el tablero se visualiza desactualizado

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#173]
Del original de 4x4 lo achiqué a 3x3. Luego escribí el siguiente programa:

```
interactive program {
    K_ARROW_LEFT  -> { MoverSiPuede(Oeste) } 
    K_ARROW_RIGHT -> { MoverSiPuede(Este) } 
    K_ARROW_UP    -> { MoverSiPuede(Norte) } 
    K_ARROW_DOWN  -> { MoverSiPuede(Sur) } 
}

procedure MoverSiPuede(dir) {
    if (puedeMover(dir)) { Mover(dir) }
}
```

Y al ejecutarlo me mostraba un tablero de 4x4 pero se movía solo dentro del de 3x3.
Al salvarlo y volverlo a cargar, lo empezó a mostrar bien.

**Comment by rodri042** [comment]
Esto no me pasa... podrás probarlo de nuevo o ver si habías hecho algo más antes?

**Comment by fidel-ml** [comment]
Ahorta parece funcionar bien. No lo pude volver a reproducir.
Cierro.
FF

2017-06-29 15:33 GMT-03:00 Rodrigo Alfonso <notifications@github.com>:
