### ISSUE TITLE
IMPORTANTE: se pueden agregar bolitas al tablero aún cuando la configuración dice que no

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#175]
Si esto está permitido, la mayoría de los estudiantes NO hace el programa, sino que pone las bolitas cliqueando... Feo.

**Comment by rodri042** [comment]
@fidel-ml

Agarré el "Simulando repartir caramelos" y cambié el json para permitirle ver los botones **pero no editar el tablero**. El json quedó:
```json
{
  "name": "Simulando repartir caramelos",
  "library": {
    "visible": false
  },
  "board": {
    "active": 1,
    "initial_board_source": "selected",
    "visible_edition": true,
    "user_permissions": {
      "can_change_source": false,
      "can_edit_board": false
    }
  },
  "execution_speed": {
    "active": "medium",
    "user_permissions": {
      "can_change_speed": true
    }
  },
  "attire": {
    "active": "Repartiendo caramelos",
    "visible": true,
    "user_permissions": {
      "can_toggle_visibility": true
    }
  },
  "blocks": {
	"visible": ["Poner"],
	"disabled": ["Poner"]
  }
}
```

Después probé esto (https://www.youtube.com/watch?v=w0F54DkYkuw) y no me dejó modificar el tablero.

Sigue pasando / podrás pasar la prueba que hiciste vos?

**Comment by fidel-ml** [comment]
Sigue pasando en "Ahora ponemos nosotros", que es JUSTAMENTE, donde no
debería pasar.
Èl JSON dice todo False, pero se puede editar...

(OJO: en "Simulando repartir caramelos" NO debería poderse quitar la
vestimenta...)
FF

2017-07-07 5:06 GMT-03:00 Rodrigo Alfonso <notifications@github.com>:

**Comment by rodri042** [comment]
> (OJO: en "Simulando repartir caramelos" NO debería poderse quitar la
vestimenta...)

Sí, eso fue una modificación mía.

Ok, pruebo con ese.
