### ISSUE TITLE
Mejorar el aviso de que un proyecto está cargando

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gobstones-web#176]
Cuando cargás un proyecto desde Github (por ejemplo https://gobstones.github.io/gobstones-web/#/code?github=flbulgarelli/buscaminas-gobstones), se presentan varios problemas: 

1. La carga es lenta, demorando varios segundos con la leyenda "Cargando Proyecto"
2. Aún luego de haber cargado, el editor _se cuelga_ unos segundos más, hasta que muestra el popup con el contenido del `README`. Durante ese período no podés hacer nada y la aplicación no responde.

En total, en una primera carga puede demorarse hasta cerca de un minuto. 

Sería deseable minimizar estos tiempos de carga, y en cualquier caso, hacer que la pantalla de "Cargando Proyecto"  se muestre hasta que el proyecto esté realmente listo para usar y se muestre el popup. 

Relacionado con ésto, sería deseable que mientras carga la aplicación por primera vez se muestre un cartel de "Cargando Gobstones Web", hasta que la aplicación haya cargado o (si es un link de `?github=`) que empiece a cargar el proyecto. 

Finalmente, recomiendo ampliamente que el texto esté centrad vertical y horizontalmente (dado que si no pasa desapercibido contra el borde superior en una pantalla en blanco), y que se muestre un spinner (por ejemplo, [el de fontawesome](http://fontawesome.io/examples/): 

```
<i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
<span class="sr-only">Loading...</span>
```

**Comment by rodri042** [comment]
Hola!
Estoy medio enquilombado de tiempos hoy, pero pude hacer [algo así](https://www.youtube.com/watch?v=5R1oJQVIoKM) y lo subí a [staging](https://gobstones.github.io/gobstones-web-staging/#/code?github=flbulgarelli/buscaminas-gobstones).

No soluciona todos los items que nombraste (lo de la carga lenta podría ver de modificarlo para directamente bajar el repo como un .zip en lugar de explorando el árbol con varios requests). Y totalmente de acuerdo en que tiene que haber un indicador que avise que la herramienta está cargando.

Pero supongo que si tenés que hacer una demo eso ya serviría, ¿no?
