### ISSUE TITLE
El popup de README no siempre aparece centrado 

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gobstones-web#177]
De forma aleatoria, el popup de README aparece corrido en la pantalla, a veces más a la derecha, otras veces más abajo. Además de ser molesto y verse mal, muchas veces la barra de scroll termina quedando oculta, con lo que no se puede ver todo el contenido.

**Comment by fidel-ml** [comment]
El tema es las imágenes. Me indicó Rodri que tienen que ser en base64, y
tengo que hacerme tiempo para mirar cómo hacer eso (estoy usando links, no
embebiendo las imágenes como me indicó Rodri...)
FF

2017-06-28 18:47 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by rodri042** [comment]
Sí, por ahora, un hack para evitar esto es agregar la imagen como base64 - [ejemplo](https://gist.githubusercontent.com/rodri042/ece71f062a14b5aa603caa391b8177fc/raw/e32721306f7053c1ed22dd28b5e72847c1a55147/description.md) -

**Comment by rodri042** [comment]
Arreglado, ahora también funciona con imágenes con links o referencias a la raíz del proyecto (https://github.com/gobstones/gobstones-web/issues/293)
