### ISSUE TITLE
Ventana de lanzamiento de proyectos al estilo pilas bloques. Tiene que aparecer apenas entras (o al tocar el botón de abrir pero una flecha tiene que indicar que toques ahí para abrir proyecto)

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#184]
Linkear la página desde gobstones web (y gobstones web desde la página)

**Comment by fidel-ml** [comment]
La idea es que las primeras veces que entre alguien tenga alguna forma de saber qué hacer. Por eso pensaba en algo tipo "modo tutorial".
