### ISSUE TITLE
La configuración de tamaño de las partes no tienen "memoria"

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#189]
Si yo achico el sector del tablero, y centro el código, y luego utilizo al botón de maximizar sector del tablero seguido de volverlo a achicar, en lugar de volver a la configuración que yo había elegido, vuelve a la configuración default. Sería interesante que recuerde cuál es la proporción que yo elegí...

**Comment by rodri042** [comment]
Lo agregué en staging!
