### ISSUE TITLE
¿Qué debería escupir gs-element-blockly para los parámetros vacíos?

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#196]
En [ésta actividad](https://gobstones.github.io/gobstones-web/#/blocks?github=gobstones/proyectos-jr&path=Proyectos/Cap.4/4.3.2.Laberinto%20con%20queso), al hacer click en "play" apenas abre, hay un error que reza "```Se esperaba ')' pero se encontró '''```"

![seleccion_338](https://user-images.githubusercontent.com/5421992/30388012-c20e3e86-9884-11e7-9972-ec8c06348d5d.png)

Esperaría algún error más genérico, por ejemplo, como mínimo: "Hay errores en el programa" ó bien algún "Falta un parámetro en X instrucción".

Descubrí que este problema es porque gs-element-blockly escupe dos comillas `' '` en la condición del if:
```gobstones
 if ('') {
      }
```

¿Qué debería escupir en el caso de que la condición esté vacía? ¿`if(){` con los paréntesis vacíos estaría mejor?

**Comment by fidel-ml** [comment]
¿Y si ponemos

if (boom("No completaste la condición de una alternativa condicional")) ...?

Y lo mismo en otros lugares que precisen cosas...
(Esto requiere agregar boom en el mundo de las expresiones. Pero es
coherente, y no creo que sea costoso.)
FF

2017-09-13 13:24 GMT-03:00 asanzo <notifications@github.com>:

**Comment by asanzo** [comment]
Eso que decís me parece un workaround simpático, pero no estoy seguro, porque mezcla errores de sintaxis con errores de programa.

Pensándolo un poco más en frío, lo que para mí debería suceder es que el intérprete de Gobstones, así como hoy ante:

```gobstones
if(){
   Poner(Rojo)
}
```

marca con una x la línea del if, nosotros podamos marcar también el bloque problemático. 

Veo dos formas de hacerlo:

1. Una, que blockly escupa el AST, ese mismo AST que se forma al parsear el texto. Cada nodo del AST debería tener información contextual, como el id del bloque.
2. Usar el parser actual, sólo que añadiendo un pragma a lo que escupe blockly, de forma que el parser al leer ese pragma añada esa info de id de bloque al AST.

En cualquiera de los dos casos gs-element-blockly debe tener un método que sea "mostrá error en bloque <id>", de forma que se pueda mostrar ese error en el momento en que se lo encuentra.

Un efecto secundario interesante es que con esta info ya se puede hacer el highlight paso a paso, con un método para highlightear un bloque (eso es fácil) y en cada paso de la ejecución debe llamarse a ese método con el id de bloque correspondiente.

**Comment by fidel-ml** [comment]
El parser que estamos terminando utiliza pragmas y construye el AST. Es
innecesario que blockly repita la tarea de construir un AST. O sea, vamos
por la opción 2, que es lo que dije en varios mails: blockly debe agregar
pragmas de regiones al texto para que el parser pueda informar
adecuadamente. Para eso tienen que ponerse de acuerdo para ver cómo es el
parser que se viene.

Lo que sí debe suceder es que blockly tenga métodos para modificar los
bloques, ya sea el "mostrá error en bloque " que proponés, como "iluminar"
o algún otro que surja.
FF


2017-09-15 13:13 GMT-03:00 asanzo <notifications@github.com>:

**Comment by asanzo** [comment]
Oka, la solución va a ser sacar los `''` molestos para que no escupa nada, y que se encargue el parser de gobstones.

Mientras, empecé a formalizar esto acá:

https://github.com/Program-AR/gs-element-blockly/issues/77

Cierro esta consulta
