### ISSUE TITLE
Simplificación de asociaciones para programas interactivos

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#199]
¿Se podrán simplificar las asociaciones para que sólo tengan una tecla, sin el modificador?
En todo caso, poderlo elegir activar desde el ejercicio.

También, estaría bueno simplificarlo en español, con algo parecido a esto:

![seleccion_348](https://user-images.githubusercontent.com/5421992/30559679-d55affa0-9c8b-11e7-83e3-fa6c59c1ded0.png)

Si me dejan hago el cambio en gs-element-blockly

**Comment by fidel-ml** [comment]
Adelante. Además, hay que agregar todas las letras y números, etc...
:)
FF

**Comment by fidel-ml** [comment]
Está bueno el texto "Al apretar tecla". Estaría genial que sea "Al apretar tecla _, ejecutar:" o algo así, ¿no?

**Comment by asanzo** [comment]
Puede ser!

Igual me hace preguntarme si en todos los bloques que pueden tener adentro subprogramas no debería haber algo parecido, y sólo deberíamos dejarlo más simple.
