### ISSUE TITLE
Discutir una sintaxis de pragmas uniforme

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#201]
Hasta el momento estamos utilizando pragmas para marcar regiones, y discutimos que hacen falta pragmas para interfacear el mundo texto con el mundo bloques (nombres con símbolos como comas o mayúsculas y espacios, posibilidad de tener íconos en bloques indicados desde texto, indicar operaciones auxiliares en la biblioteca del docente, etc.).
Sin embargo, la sintaxis de cada uno se hace en forma ad-hoc. Estaría bueno que discutamos una sintaxis uniforme para estos pragmas...
@foones te mandás una propuesta? :D

**Comment by asanzo** [comment]
Hola!

Perdón que me meta. Antes de hacer una propuesta, según entiendo, hay que listar los problemas a resolver. Los problemas que tienen que resolver los pragmas, son de la ida y la vuelta hacia los bloques.

- Procedimientos **auxiliares**: marcar un procedimiento para que no se transforme en bloque.

Por ejemplo,

```Gobstones
//@NoBlock
procedure AuxiliarPonerFlor(){
     .....
}
```

- Nombres amistosos/**complejos**: hoy los procedimientos nombrados ComoEste_DeAca se transforman en un bloque cuyo texto es "Como este <parámetro> de aca". Esta convención me gusta, pero deberíanse poder hacer cosas raras en casos especiales, como poder hacer que un nombre de procedimiento que en Gobstones textual no admite caracteres extraños, sí terminen mostrándose en los bloques. Por ejemplo, marcar un procedimiento que se llame Poner__Veces, para que _no se interprete de la forma por defecto_, sino que podamos escribir un string en el pragma diciendo cómo tiene que mostrarse. Sería un custom block name: "Poner _ , _ veces", lo que escupería un bloque "Poner <parámetro> , <parámetro> veces". Esto permitiría también poner tildes, eñes y otras cosas, en el nombre de los bloques. Ver #190 y https://github.com/Program-AR/gs-element-blockly/issues/72

Por ejemplo:

```Gobstones
//@CustomBlockName: "Poné _ flores por la mañana, chabón"
procedure PoneFloresPorLaManiana(cant){
     .....
}
```

- **Id de bloque**: Para poder mostrar errores en los bloques, ó para poder iluminarlos a medida que se ejecuta. Esto no lo usaría el docente, sino que se hace automáticamente en el código generado por los bloques, justo antes de ejecutar. Ver https://github.com/Program-AR/gs-element-blockly/issues/77

Por ejemplo:

```Gobstones
///@BlockId=af34
program {
    ///@BlockId=2ty5
    PonerN(Rojo,3)
    ///@BlockId=jh9k
    PonerN(Verde,5)
}

///@BlockId=34tt
procedure PonerN(color,cant){
    ///@BlockId=6ryy
    repeat(cant){
        ///@BlockId=54yi
        Poner(color)
    }
}
```

- **Regiones** (esto no sé lo que es)

No sé si me estoy olvidando algún problema a considerar.

**Comment by fidel-ml** [comment]
Analizando la documentación del nuevo intérprete, ya está implementada la siguiente sintaxis:

"El tokenizador reconoce directivas pragma de la forma "/*@parte 1 @parte 2 @...@parte n @*/". La idea es que esto pueda ser un mecanismo extensible de directivas. Ver más abajo las directivas soportadas."

O sea, si es correcto, los block_id se podrían poner como:

/*@BEGIN_REGION@34tt@*/
procedure PonerN(color, cant){
    /*@BEGIN_REGION@6ryy@*/
   repeat(cant){
        /*@BEGIN_REGION@54yi@*/
        Poner(color)
       /*@END_REGION@*/
    }
   /*@END_REGION@*/
}
/*@END_REGION@*/


¿@foones es así? ¿Podemos agregar otros ahora? (Por ejemplo, BlockId, BlockName, BlockIcon?

**Comment by fidel-ml** [comment]
Supongo que para saber los anidamientos...  Nuevamente, es Barenbaum el que
debería responder.

**Comment by rodri042** [comment]
Esto quedó resuelto
