### ISSUE TITLE
Estado justo antes de explotar

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#202]
Al explotar hay alguna información sobre el problema, como por ejemplo las coordenadas por donde se cae del tablero. Pero estaría bueno que haya ayuda visual sobre el mismo tablero.

¿Se podrá poner un botón que lo muestre justo antes de explotar?

![seleccion_362](https://user-images.githubusercontent.com/5421992/30708258-92c041d2-9ed4-11e7-817d-d0a1aca05820.png)

Esto es independiente del nuevo intérprete, que permitirá mejorar los informes de errores incluso marcando el bloque problemático (¡Yay!) .

**Comment by fidel-ml** [comment]
No estoy de acuerdo. No es el tablero lo que hay que mirar, sino el código.
Indicar el lugar donde se produjo el error será un avance importante.
Además podría tener el call-stack...

**Comment by fidel-ml** [comment]
Pensá qué pasa si el error está en una función. Mostrar el tablero no sirve
de nada porque puede que hayan habido cientos de cambios.

**Comment by asanzo** [comment]
Humm... A ver, compro que el stack ayudaría más (no me lo imagino en texto, pero sí como la iluminación simultánea de los bloques involucrados). Y compro que ayuda  saber qué mover o sacar falló.

O sea, en:

```Gobstones
 1 program {
 2     Poner(Rojo)
 3     Sacar(Rojo)
 4     Mover(Este)
 5     PonerYSacar()
 6 }
 7
 8 procedure PonerYSacar(){
 9     repeat(4) {
10           Poner(Rojo)
11     }
12     repeat(5) {
13           Sacar(Rojo)
14     }
15 }
```

* Está bueno que diga que el problema es un Sacar.
* Está bueno que ilumine el Sacar de la línea 12, y no el de la línea 3.
* Creo que estaría bueno que ilumine el stack hasta el momento, por ejemplo program + PonerYSacar() + procedure PonerYSacar() + repeat(5) + Sacar(Rojo).

Pero en realidad, eso no es suficiente. En este programa que es sencillo, yo sé, leyendo, que la celda sobre la que ocurre el error es la del Este de la inicial. Pero, ¿Qué pasa en un programa más complejo? ¿No me ayuda saber dónde estaba el cabezal? ¿No me ayuda saber qué bolitas se pusieron ya? ¿No puedo detectar un problema que en realidad está en otra línea y no en esa iluminada, gracias a mirar el estado del tablero antes de romper? ¿No es el tablero intermedio una verificación intuitiva del correcto funcionamiento de cierta parte del programa?

Mi inquietud nace de lo siguiente: cuando estoy debuggeando en la vida real, el stack es poca info. Muchos problemas se resuelven en el momento en el que hacés un match entre el estado esperado y el estado real. Y de hecho, eso te permite muchas veces desligarte de entender todo el código y revisarlo paso por paso, operativamente.

Y respecto de las funciones, el resultado de una función no depende, en Gobstones, únicamente de sus parámetros, sino también del estado del tablero. Entonces sí sirve conocer el estado del tablero antes de ejecutar una función. 

Y en el caso de un error en una función impura, también importa el estado "virtual" construido hasta entonces, por las mismas razones.

Creo que estoy fallando en ver una parte de la metáfora. 

@francofrizzo

**Comment by fidel-ml** [comment]
Reitero que estoy absolutamente en contra de mostrar el estado. Va en la
linea de tener un debugger, y la idea básica de Gobstones es no tener
necesidad de debugging... Ya acepté la herramienta de ejecución paso a
paso, fundamentalmente por los primeros ejercicios, y hasta que los
estudiantes adquieren una visión operacional adecuada. Pero después ese
paso a paso se debe eliminar.
Para aprender a detectar errores profesionalmente, la herramienta adecuada
es el uso de precondiciones. En el Junior los ejercicios son lo
suficientemente pequeños como para que una indicación de dónde está el
error alcance.
