### ISSUE TITLE
El botón ejecutar en pantallas chicas tapa el tablero

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#203]
Quizás podemos desechar este issue, pero no quería dejarlo de reportar.

![seleccion_363](https://user-images.githubusercontent.com/5421992/30708427-47097280-9ed5-11e7-9eaa-454b6e287d67.png)

@francofrizzo

**Comment by fidel-ml** [comment]
Yo lo noté, y me molesta. Pero no sé cómo arreglarlo...
Habría que taggear a Fede Aloi también (no puedo taggear en el teléfono).

**Comment by rodri042** [comment]
Con el zoom de tablero con la ruedita esto ya queda medio arreglado
