### ISSUE TITLE
Distintas formas de visualización en el lanzador de proyectos

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#210]

**Comment by fidel-ml** [comment]
[image: Web Bug from
https://github.com/notifications/beacon/AIaqtnbfjZjNc_HJisLD4NV_IhsLA_crks5smGArgaJpZM4Pjlek.gif]Técnicamente,
no sería solo "agrandar o achicar las imágenes". Sería algo como "Poder
seleccionar entre varias formas de visualizar los ejercicios. Incluir al
menos: íconos grandes (la actual), íconos pequeños y lista (otras a
placer)."
