### ISSUE TITLE
Pensar un else if para bloques extensible (boton derecho, quiero un else if mas)

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#211]
ISSUE RELACIONADO: https://github.com/Program-AR/gs-element-blockly/issues/89

**Comment by rodri042** [comment]
Mirando el PDF de sintaxis, noté que gobstones no soporta "else if". Esto ¿estaría bueno agregarlo también al lenguaje?,  @fidel-ml 

Si no, algo como esto:
![image](https://user-images.githubusercontent.com/1631752/31915955-d0a2469a-b850-11e7-9302-2f746d2b1869.png)

va a compilar a:

```
if (hayBolitas(Rojo)) {
  Mover(Oeste)
} else {
  if (hayBolitas(Verde) {
    Mover(Norte)
  } else {
    if (hayBolitas(Negro) {
      VaciarTablero()
    } else {
      Mover(Este)
    }
  }
}
```

:confused:

**Comment by rodri042** [comment]
Pregunta 2: Si hacemos el if y que se le puedan sumar else if's y else con botón derecho, ¿sacamos el bloque que tiene if y else? ("AlternativaCompleta" se llamaba ese bloque)

**Comment by fidel-ml** [comment]
Ya estaba agendado agregar else if. :)
Sobre sacar la alternativa completa... Yo me imagino que el if con elses
extensibles empieza siendo una alternativa completa y puede crecer. ?O es
muy diferente?

**Comment by rodri042** [comment]
Oka, entonces hago que genere ese código pero con `else if` por más que hoy por hoy no ande.

Hoy tenemos:
AlternativaSimple: Bloque que genera if (cond) { bloque } y no se puede extender
AlternativaCompleta: Bloque que genera if (cond) { bloque1 } else { bloque2 } y no se puede extender.

La preocupación iba por:
- A cuál de los dos bloques le metemos el comportamiento de agregar else if, o si creamos uno nuevo (lo que sería medio redundante)
- O si decidimos agregarselo a la simple (que arranque sin nada y uno pueda sumarle else if's o else's), el bloque "AlternativaCompleta" pasa también a ser redundante

**Comment by fidel-ml** [comment]
La alternativa simple debe quedar simple. Si tiene else, puede agregar más
elses.
Verificá que el nuevo intérprete tenga elseif... (Preguntale a Pablo).

**Comment by rodri042** [comment]
Estuve peleando bastante con esto y llego a tener algo así:

![image](https://user-images.githubusercontent.com/1631752/32265481-dc86b512-beeb-11e7-8c95-db90100717bc.png)

que claramente **no** es lo que queremos. Por alguna razón blockly no me da una forma de agregar inputs en el medio, solo al final :disappointed: 

@asanzo me das una mano a ver si me estoy perdiendo de algo? lo tengo en una branch `else-if`

**Comment by asanzo** [comment]
@rodri042 cuidado, _ninguna modificación que hagas on the fly sobre el bloque se persiste al xml_. En el xml se guardan el type de bloque, las cosas dentro de los values, y las cosas dentro de los statements. 

Blockly va a romper cuando vos quieras traerte el xml con 5 elseifs sobre un workspace que tiene definido un bloque "elseif" que sólo tiene un statement.

Lamentablemente la única forma de cambiar bloques on the fly y que esto persista es usar [Mutators](https://developers.google.com/blockly/guides/create-custom-blocks/extensions).

Afortunadamente los muchachos de blockly ya lo implementaron esto. 

![elseif](https://user-images.githubusercontent.com/5421992/32310904-68b2a824-bf74-11e7-9b07-36b8e7297359.gif)

Mirá [acá el código de eso](https://github.com/google/blockly/blob/master/blocks/logic.js):

![seleccion_399](https://user-images.githubusercontent.com/5421992/32311240-3ee79958-bf76-11e7-81b4-da000cdc1a81.png)

* mirá la definición de `controls_if`, y de cada una de las cosas q aparecen en la imagen.
* buscá las apariciones de `CONTROLS_IF_MUTATOR_MIXIN` para que te cierre más o menos cómo se implementa:

* `mutationToDom` pasa de esto 

![seleccion_402](https://user-images.githubusercontent.com/5421992/32311282-9ddab68e-bf76-11e7-83f1-79bbf0801cb8.png) 

a esto: 

![seleccion_403](https://user-images.githubusercontent.com/5421992/32311305-c4b5c2d0-bf76-11e7-8cfb-e612876a9094.png)

* `domToMutation` hace al revés.

* `compose` pasa de esto ![seleccion_402](https://user-images.githubusercontent.com/5421992/32311400-2928587c-bf77-11e7-8c45-c618af55f969.png) a esto: ![seleccion_401](https://user-images.githubusercontent.com/5421992/32311432-571e3e2c-bf77-11e7-9236-cf923609a6b3.png)

* `decompose` al revés.

Hay que hackearlo para que el diálogo de mutator no se muestre, sino que se agregue un botoncito + y un botón - ó bien con botón derecho, que por dentro persista con mutators pero por fuera no se vea el dialoguito de mierda 
![seleccion_400](https://user-images.githubusercontent.com/5421992/32311517-bd4fe1a0-bf77-11e7-9d29-8b330d135692.png)

En el proyecto que te tiré en https://github.com/Program-AR/gs-element-blockly/issues/89 de toebes-extreme, el flaco logró hacerlo.

Pero por el tiempo que disponemos, creo que sólo usaría el controls_if que nos dan ellos, con la traducción tuneada con nuestro propio `es.js` y al choto.

**Comment by rodri042** [comment]
Wow!

Sip, algo de eso estaba teniendo en cuenta. Lo loco que descubrí (hace re
poco) es que "usar mutators" no necesariamente implica tener una ventanita
para agregar cosas (ejemplo:
https://github.com/Program-AR/gs-element-blockly/blob/dev/js/gobstones-blocks.js#L113).
Cada vez que el bloque cambia llama a ese *mutationToDom* donde vos
actualizás el xml como te plazca, y en *domToMutation* rearmás todo el
estado.

Y la parte que me se me estaba complicando es la de agregar el bloque en el
medio *peeero* con esto que me decís de que ya fue implementado por
blockly, ¡genial! XD

Voy a probar mirando eso. Gracias por todo el detalle n.n

**Comment by asanzo** [comment]
https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators

Exacto, la doc dice eso.

**Comment by rodri042** [comment]
Wii, al final salió esto :D @asanzo ya lo mergeé a `dev`.

@fidel-ml esto tiene algunos breaking changes, después te ayudo a arreglar los XMLs (por ahora no lo subo, subiré todo junto cuando terminemos de integrar el intérprete nuevo)

**Comment by rodri042** [comment]
@fidel-ml sobre lo último que dije:

Al final me di cuenta que no era nada trivial migrarlo y lo cambié para hacerlo retrocompatible. Al final quedó subido a staging, así que ya podrías usar el else if en los proyectos.
