### ISSUE TITLE
Agregar un campo mas para la parte del selector de fuente de tablero. Uno para si es random o no (que ya existe) y otro para si es visible o no.

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#212]

**Comment by rodri042** [comment]
@fidel-ml estaba viendo que este campo ya existe.

`initial_board_source` decide cuál es la fuente de tableros inicial (random o selected) y `can_change_source` oculta el botón si el alumno no puede cambiar la fuente del tablero. ¿Se me está pasando algo?

**Comment by fidel-ml** [comment]
No es lo mismo. Es solo para el sábado de randómico: visible o no, activo o
no. Hoy activo es visible e inactivo es no visible. Una cosa es si empieza
randómico o no, y otra si puede cambiar la randomización o no (incluso
aunque no pueda editar el tablero).
Se entiende?

**Comment by rodri042** [comment]
Creo que entiendo, pero eso que decís se puede...

Si querés random inicialmente pero modificable ponés:
*initial_board_source: "random"*
*can_change_source: true*

Si querés random y no modificable (por ende, no visible el botón) ponés:
*initial_board_source: "random"*
*can_change_source: false*

Si querés no-random inicialmente modificable ponés:
*initial_board_source: "selected"*
*can_change_source: true*

Y para el último caso:
*initial_board_source: "selected"*
*can_change_source: false*

¿Vos decis de agregar un campo más para visible y que pueda aparecer el
botón pero "bloqueado"?

2017-10-19 17:43 GMT-03:00 fidel-ml <notifications@github.com>:

**Comment by fidel-ml** [comment]
Si pongo la combinación

*initial_board_source: "random"*
*can_change_source: true*


entonces empieza random y lo puedo cambiar, PERO también puedo modificar el
tablero. Y yo quiero que no puedan modificar el tablero, pero sí si es
randómico o no el que se elija (cómo se hace con el selector de velocidad).

O sea, habría que separar el
*can_change_source
en
*can_change_initial_board
*can_modify_stones
*can_modify_board_size

Básicamente, quiero que el selector del tablero inicial sea como el de
velocidad: visible o invisible, fijo o modificable.

**Comment by rodri042** [comment]
El *can_change_source* no tiene que ver con poder editar el tablero o no:
ese *can_modify_stones* que decís ya existe y se llama *can_edit_board*.

Lo que estoy por casi terminar para la problemática que decís es esto: (en
rojo los campos nuevos)

*active*: 4 // tablero activo
*initial_board_source*: "random" // valor inicial de fuente de tableros
*visible_edition*: true // muestra u oculta TODA la parte de arriba del
panel de tableros
*collapse_toolbox*: true // la parte de arriba del panel de tableros
aparece inicialmente colapsada
*user_permissions*: {
  *can_change_initial_board: *muestra el botón de cambiar de tablero
inicial (el de arriba a la izquierda del panel derecho), y si
*can_edit_board* también muestra el tachito y el + y - para agregar/sacar
tableros
  *can_change_initial_board_source: *muestra o no el botón de cambiar la
fuente de tablero inicial (random o no)
  *can_edit_board*: puede agregar bolitas y cambiar tamaño
  *can_view_size_section*: puede ver la parte de cambiar tamaño
  *can_view_attire_section*: puede ver la parte de cambiar vestimenta
}

Creo que cubre todos los casos, ¿qué te parece?

PD: Para ser consistentes con lo que venimos haciendo respecto a las
opciones, lo mejor es que si una opción no se le permite al alumno, no
mostrarsela (así hacemos con los paneles de edición). En este caso, para mí
si el alumno no puede cambiar la randomicidad, ni deberíamos mostrarle el
botón.


2017-10-19 20:55 GMT-03:00 fidel-ml <notifications@github.com>:

**Comment by fidel-ml** [comment]
Me parecen bien las opciones.
Sobre lo otro, si lo forzás, estoy obligado... Si lo permitís, puedo
conseguirlo igual, pero no me limita a futuro (por ejemplo, si quiero hacer
un manual donde una vez que presenté un feature, sigue ahí aunque
deshabilitado, por ejemplo). Igual, por ahora creo que no importa.
