### ISSUE TITLE
En el interactive, agregar las letras y los numeros. Como no van a entrar, pensar otra forma de ponerlos (probar que la persona ingrese su tecla)

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#225]
> Las asociaciones de teclas siguen sin cambios. Es importante, para
poder terminar los proyectos del cap.9 que estén todas... Habíamos
hablado de tener varios vínculos: letras, números, símbolos, teclas
especiales. Además, los modificadores deberían no estar visibles,
hasta que se los pide. Tendrían que haber solo 3, y que se pudiera
seleccionar cualquier combinación de ellos...

**Comment by fidel-ml** [comment]
Este es bastante importante para poder terminar los proyectos del manual.
Si tocar tecla para elegirla es costoso, pensar en tener 3 o 4 bloques:

  - "Al tocar letra ___, ejecutar" (con combo de A a Z)
  - "Al tocar dígito ___, ejecutar" (con combo de 0 a 9)
  - "Al tocar tecla ___, ejecutar" (con combo para flechas, enter y otras
yerbas)
  - "Al tocar símbolo ___, ejecutar" (con combo para símbolos comunes)

En todas, con botón derecho se podría agregar o sacar "SHIFT", "CTRL" o
"ALT" (las combinaciones resultantes se expresan después en 'terminos del
lenguaje, pero por interfaz pueden ser independientes)

¿Deberían estar en programa? Quizás sería bueno tener una categoría
"Asociaciones de teclas" o algo así...

**Comment by rodri042** [comment]
@fidel-ml esto ya quedó implementado, podés chequearlo en staging.

Sobre los símbolos hay una limitación técnica, la biblioteca que usamos para detectar las teclas no soporta casi ninguno de los "chirimbolos" tipo asterisco, +, paréntesis, etc. Hay que meter mano y arreglarlo o usar otra. Mientras tanto, ahora que lo estuve cambiando directamente los saqué, ya que si no van a andar no tiene sentido ponerlos.
