### ISSUE TITLE
Tutorial: desactivarlo si se lo cierra con ESC

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#244]
Actualmente, si el usuario cierra el tutorial pulsando ESC, no se lo desactiva y hay que hacerlo a mano. Creo que si alguien cierra el tutorial es porque considera que no lo necesita, por lo que sería razonable ya dejarlo desactivado. Eso lo haría menos tedioso para usuarios ya experimentados que usan la interfaz desde una máquina o navegador nuevos.

**Comment by fidel-ml** [comment]
El tema es que si lo hace por accidente, puede perdérselo... Quizás al dar
escape se le pueda preguntar "Quiere desactivarlo?"
Rodri?
