### ISSUE TITLE
Con el nuevo intérprete, la visualización del paso a paso se desmadra...

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#254]
Revisar la visualización del paso a paso, porque no se llega a apreciar nada en algunos casos, especialmente en velocidades más rápidas, ya que tarda en cargar por lo que empieza mostrando por la mitad, y luego se come frames.

**Comment by rodri042** [comment]
En el `gs-board` 1.8.7 mejoré muchos temas de performance y ahora andan más lindo. Lo subo a staging.
