### ISSUE TITLE
Bug en la obtención de variables de una asignación

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#255]
* Cuando pongo una asignación en un procedimiento y trato de obtener una variable para usarla en otro lado, aparece y desaparece.
* Si pongo la asignación suelta, me deja obtener la variable, pero después se comporta de maneras raras... 

A diferencia de los procedimientos, las variables no deberían estar referidas a un procedimiento. Si pensás en referir variables, habría que hacerlo a sus asignaciones, pero como hay más de una, y puedo borrar una y crear otra, se hace raro...
Habría que pensar en cambiar todo el mecanismo de variables (para parámetros está joya lo de referir, pero para variables no...). Hay que pensarlo más.

**Comment by fidel-ml** [comment]
Ya entendí: el campo "parent" del "<mutation var...>" de un "variables_get" refiere a una asignación. Pero el "parent" de un "variables_get" debería ser el procedimiento o función que contiene alguna asignación de esa variable, y no la asignación en sí.
Por eso, si consigo un "variables_get", solo lo puedo usar en la asignación de turno... Y eso es justamente el caso más raro de uso...

El scope de una variable es un procedimiento o función. Pero a diferencia de un parámetro, no se declara, y eso es lo que genera la confusión.  Quizás lo mejor sea dejar que puedan usar cualquier variable en cualquier lado, y que una vez generadas no se puedan cambiar de nombre... O pensar alguna otra manera.

**Comment by rodri042** [comment]
Esto quedó arreglado, ahora las variables no tienen parent
