### ISSUE TITLE
Sobre parámetros fuera de scope

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#260]
Cuando un parámetro se utiliza efectivamente en el código de otro procedimiento que no es el que lo define, en lugar de estar solo deshabilitado, debería tener un color que indique que eso es un error (por ejemplo, rojo, o con borde rojo, o algo así). Si no, alguien que no entendió aún el tema scope, puede no entender por qué no se habilita. El rojo habla de un error, más que de una deshabilitación...

**Comment by rodri042** [comment]
Poner de rojo los parámetros con $parent inválidos

**Comment by rodri042** [comment]
Ahora se ven en rojo:

![screenshot3](https://user-images.githubusercontent.com/1631752/57989907-b0f42d00-7a77-11e9-85f4-dfa8341d07fd.png)
