### ISSUE TITLE
Sobre el highlight durante la ejecución

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#264]
El highlight durante la ejecución actualmente solo ilumina comandos primitivos y llamadas a procedimientos, pero no ilumina las estructuras de control... Al ejecutar un if, debería, antes de iluminar la rama elegida, iluminarse el bloque del if. Al ejecutar una repetición, luego de cada iteración debería volver a iluminar al bloque de repetir (tanto simple como condicional).  Y al ejecutar un procedimiento, debería dejar iluminada la invocación que lo activó.

Si esto resulta costoso, entonces momentáneamente desactivemos el highlight, porque así como está es confuso.

**Comment by rodri042** [comment]
Duplicado de https://github.com/gobstones/gobstones-web/issues/336
