### ISSUE TITLE
Al cargar solución se pierde título de la actividad actual

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#273]
El título de una actividad se cambia al cargar una solución. Estaría bueno poder saber que sigo en esa actividad aún al cargar una solución de otra

### Para Reproducir:
1) Estoy en Transformar las Letras
![seleccion_543](https://user-images.githubusercontent.com/5421992/43282542-cd2d846e-90ec-11e8-8526-a4c5c1fd9463.png)

2) Cargo la solución de otro ejerciio
![seleccion_543](https://user-images.githubusercontent.com/5421992/43282645-16884c66-90ed-11e8-87de-47b43d20286b.png)

3) Al cargarla cambia el nombre del ejercicio:
![seleccion_544](https://user-images.githubusercontent.com/5421992/43282656-1cece29c-90ed-11e8-9d5a-3212590376f7.png)

Aunque yo siga estando en el mismo ejercicio

### lo que debería pasar

Debería **seguirse viendo de alguna forma el título de la actividad donde estoy**, aunque no sea en el mismo lugar.

**Comment by rodri042** [comment]
Creo que eso hace mucho era el comportamiento deseado (al cargar código, setear el nombre del archivo como nombre del proyecto).

Ahí lo saqué, ya no va a cambiar el nombre del proyecto al cargar código/bloques
