### ISSUE TITLE
Version Linux no corre en Ubuntu por default

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#276]
Al intentar correr el ejecutable en un Ubuntu falla por ausencia de libgconf-2-4 y canberra-gtk-module. Luego, incluso instaladas explota con un segmentation fault en core.

Habría que probar diversas distros (Al menos las mas comunes, Ubuntu, Mint, Huayra, Debian, Fedora, Arch, etc) para ver que la versión de Linux corra efectivamente.

En un ideal mucho más volado, habría que hacer distribuibles para las distros donde se instalen las dependencias requeridas previo a instalar la app.

**Comment by rodri042** [comment]
Esto quedó solucionado en https://github.com/gobstones/gobstones-web/pull/290, ahora se distribuye como AppImage y por lo que probé en Ubuntu y Fedora anda bien. Cierro
