### ISSUE TITLE
Scrollbar Oculto en barra lateral

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#277]
En el menu lateral o sidebar no hay un scrollbar. Esto hace que la gente que no tiene mouse o un touch con scroll no pueda bajar.

En pantallas pequeñas como las notebooks de conectar igualdad, esto trae aparejado que no se pueden acceder a las opciones que se encuentran más abajo.

**Comment by fidel-ml** [comment]
Arreglado
