### ISSUE TITLE
Modal de error debería cerrar tras modificar código

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#282]
Al cometer un error, un modal o popup se abre en el código desde el bloque que lanzo el error, con un mensaje significativo sobre lo ocurrido.

Comportamiento actual:
Cuando el usuario mueve o actua sobre el código para corregirlo, el popup no desaparece, haciendolo solo cuando se vuelve a ejecutar el programa tras haber corregido el error.

Comportamiento esperado:
Cuando el usuario mueve o actua sobre el código intentando corregir el error, el popup desaparece.

**Comment by fidel-ml** [comment]
Esto está duplicado en #312
