### ISSUE TITLE
Feature request: posibilidad de exportar los bloques del canvas en formato vectorial

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#283]
Para acompañar el manual para docentes que están elaborando UNQ + Fundación Sadosky, sería muy útil poder contar con una manera de exportar los bloques que aparecen en el canvas de Blockly a un archivo vectorial (SVG o similar). Esto es relativamente simple de hacer, porque Blockly ya trabaja con un canvas SVG para mostrar los bloques en el navegador.

A modo de referencia, en [este archivo](https://github.com/Program-AR/pilas-bloques/blob/7171b0b557e2a16aef4a17080c371de4999c0478/vendor/utilidades_de_depuracion.js) está el código de la forma en que lo hicimos en PilasBloques (la función relevante es obtenerBloquesSvg, línea 39).

**Comment by fidel-ml** [comment]
¡Ya está agregado en las versiones nuevas!
Revisá el menú de la izquierda...

**Comment by francofrizzo** [comment]
¡Excelente!
