### ISSUE TITLE
Botón de "cancelar" en agregar timeout no tiene el comportamiento esperado

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#284]
Cuando en "programa interactivo" hacés clic para agregar timeout, te aparece un cartel que te pide que ingreses la cantidad de milisegundos. Hay un botón de "Aceptar" y uno de "Cancelar". Sin embargo, cancelar no desaparece el popup sino que borra el contenido que hayas escrito. Estaría bueno que "Cancelar" quitara el popup, dando la posibilidad de retractarse de haber agregado un timeout.

Actualmente para hacer rollback hay que terminar de crear el timeout y luego eliminarlo.

![imagen](https://user-images.githubusercontent.com/12092129/44171515-c4b9cf80-a0b0-11e8-869f-a8fa6a60ee58.png)

**Comment by rodri042** [comment]
Arreglado
