### ISSUE TITLE
Las funciones definidas en el proyecto se muestran distinto que las definidas por el usuario

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#285]
Las funciones sin parámetros se muestran de maneras diferentes según paso a detallar: cuando ya vienen creadas en el proyecto se muestran en una sola línea mientras que cuando uno crea el mismo tipo de función desde Definiciones -> Funciones, ésta se crea en 2 líneas.

Esto se puede ver en el proyecto "Definición por penal" en las funciones izquierda (viene dada) y derecha (la creé yo).
![imagen](https://user-images.githubusercontent.com/12092129/44172015-478f5a00-a0b2-11e8-922e-ce5beee0d725.png)

Estaría bueno que se muestren del mismo modo (en una sola línea estaría bien) ya que así como está puede confundir, dando la sensación de que son tipos de construcciones diferentes cuando, en realidad, son exactamente lo mismo.

**Comment by fidel-ml** [comment]
Esto es intencional... Hay varias cosas de los procedimientos primitivos
que no son iguales en los definidos por usuario (por ejemplo, los
argumentos infijos -- que no se pueden lograr). Pero para cosas como la
forma de layout, se puede cambiar de uno a otro modo usando el menú
contextual de cada bloque ("Entradas en línea" o "Entradas externas").

**Comment by rodri042** [comment]
Idem. Eso se puede configurar al crear la definición de función. El default es *varias líneas* así que eso debió haberlo hecho el creador del ejercicio.
