### ISSUE TITLE
Mensaje de error poco claro para asignación vacía

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#286]
Si al crear una variable nos olvidamos de asignarle un valor, el mensaje de error que da Gobstones es críptico.

Según el manual UNQ, esta situación debería hacer que el programa de BOOM y no este error. Habría que definir cuál es el comportamiento esperado, si el del manual o el que ahora sucede en Gobstones.

![imagen](https://user-images.githubusercontent.com/12092129/44172341-414dad80-a0b3-11e8-87b7-810b54c3d6a8.png)

**Comment by fidel-ml** [comment]
Los mensajes específicos de error van a cambiar. Estamos trabajando en una
forma de modificarlos por proyecto...
Para la parte de que en lugar de error de sintaxis dé error de ejecución
(BOOM), el código textual generado por el bloque debería ser diferente. Y
esto es para Alf... @AlfredoSanzo.
