### ISSUE TITLE
Typo en bloque "número de bolitas"

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#287]
Considerando que en todas las instrucciones de Gobstones siempre utilizan la tilde cuando corresponde, habría que agregarle la tilde a "numero" en la expresión primitiva "numero de bolitas".

![imagen](https://user-images.githubusercontent.com/12092129/44172379-6e01c500-a0b3-11e8-87a1-7b2b89d23a88.png)

**Comment by fidel-ml** [comment]
Excelente observación. El tema es que la primitiva Gobstones es nroBolitas.
:D Es cuestión de cambiar la forma en que se muestra el bloque.
FF

2018-08-15 17:48 GMT-03:00 Franco Frizzo <notifications@github.com>:

**Comment by rodri042** [comment]
Arreglado en https://github.com/Program-AR/gs-element-blockly/blob/dev/js/gobstones-blocks.js, en el próximo deploy lo integro
