### ISSUE TITLE
El archivo de configuración config.json debería almacenarse en el directorio del usuario

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#289]
El programa realiza la lectura y escritura de un archivo de configuración que guarda en "app/config.json".

Cuando la aplicación se instala para correr con modo offline, se deben contar con privilegios para escribir dicho archivo.
En la mayoría de los sistemas operativos, esto implica que el programa no puede instalarse en un lugar estandar (C:\Program Files, /opt/, etc.).

El archivo de configuración debería almacenarse en la carpeta del usuario (C:\Users\<user>\AppData, /home/.config, etc.)

Además, si no pudiera leerse o escribirse el archivo, el programa no debería explotar, si no correr con la configuración por defecto. Algo que ahora no sucede.

**Comment by rodri042** [comment]
Totalmente de acuerdo, tendría que estar en el `appData` que proporcione electron. Hasta no arreglar esto, las `AppImage` de Linux no van a funcionar bien

**Comment by rodri042** [comment]
Arreglado en https://github.com/gobstones/gobstones-web/commit/51d103c766e16b744f34347e7e3caee5ec069d54

Queda aún solucionar el mismo tema pero con la carpeta `guides` que se descarga en el directorio de la aplicación, y tendría que preguntarle al usuario dónde guardarla. Pero eso lo voy a revisar en estos días.

Cierro el issue!
