### ISSUE TITLE
Agregar forma de referenciar el ejercicio actual desde markdown

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#293]
Actualmente se deben encodear las imagenes que se agregan a markdwon como base64 para que estas sean tomadas cuando se ejecuta offline.

Sería bueno poder referenciar al directorio actual del ejercicio (cuando se corre offline, el directorio donde se descargaron los archivos, cuando se corre online, el repositorio de github en su versión raw) de forma tal de poder agregar imagenes sin esa codificación, lo cual vuelve el archivo más facil de editar y a las imagenes más sencillas de mantener.

Esto también posibilitaria ver los enunciados en PDF descargados aunque no se cuente con conexión, pues actualmente son enlaces a la versión raw del repo github y se debe contar con internet para descargarlo (incluso si fueron decargados cuando se bajaron offline).

**Comment by alanrodas** [comment]
Como propuesta, se podría agregar una especie de variable $CURRENT_PROJECT o algo así, que previamente a pasarlo por el parser de markdown se reemplace por la URI correspondiente.

En ese sentido podrían ser útiles otras variables como $CURRENT_COURSE (Con la URL del curso) o cosas así que puedan llegar a querer ser referenciadas.

**Comment by rodri042** [comment]
Agregué $CURRENT_PROJECT pero todavía tenemos que solucionar https://github.com/gobstones/gobstones-web/issues/177 para que el modal se abra en la ubicación correcta

**Comment by rodri042** [comment]
Solucionado #177 también. Cierro
