### ISSUE TITLE
El repetirHastaQue no acepta la ExpresionCompletar como condición

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#294]
Seguramente tiene que ver con el control de tipo que hace el bloque. Pero ese control es incorrecto, porque no siempre se sabe el tipo de las cosas. Debe deshabilitarse...
Si no es el control de tipo, no sé. Pero debería poder poner ExpresionCompletar como condición de un repetirHastaQue

**Comment by rodri042** [comment]
El control de tipos quedó eliminado para "repetir hasta que" hace algunas versiones, así que esto ya no debería pasar. Cierro...
