### ISSUE TITLE
Id autogenerados de blockly hacen fallar la aplicación si comienza con */

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#296]
Un código generado por un alumno en Jr presenta un error críptico al intntar correr el programa:
```
Se esperaba alguna de las siguientes alternativas:
una coma (",")
un paréntesis derecho ("(")
Se encontró un identificador con mayúsculas.
```

El programa era correcto, y el código generado también. Tras editar el gbk pude aislar el problema.

El problema ocurre cuando el ID autogenerado por blockly comienza con asterisco seguido de una barra (*/)

Tipo: Bug

Reproducible: SI

Pasos para reproducir el error:
1. Iniciar un proyecto de cero (solo el bloque program está incluido)
2. Ejecutar el programa y verificar que funciona correctamente.
3. Guardar el archivo .gbk de dicho proyecto (solo el bloque program)
4. Editar el archivo .gbk y reemplazar las primeras dos letras del Id del bloque program con */
5. Recargar Gobstones-Jr y abrir el archivo .gbk modificado.
6. Ejecutar el programa

Comportamiento esperado:
El programa funciona correctamente, igual que en el paso 2

Comportamiento obtenido:
Aparece el mensaje "El programa tiene errores"

Comportamientos alternativos:
Dependiendo de cual sea el bloque con el id que comienza con  */  puede aparecer el mensaje de error mencionado más arriba.

Comentarios:
Como los IDs son autogenerados, la posibilidad de que justo un bloque comience con */ es remota, pero existe.
Se desconoce si otras combinaciones producen errores similares. (/* pareciera no generar error, tampoco //, por lo que no pareciera estar relacionado a comentarios, +/ tampoco).

**Comment by rodri042** [comment]
Arreglado en https://github.com/gobstones/gobstones-web/commit/b65d8d0770bf62a7a88a7500421d15ee731995c7 y https://github.com/Program-AR/gs-element-blockly/commit/d2a9b2e25121f76726264cac737846f2eb82d4a6
