### ISSUE TITLE
Nombre del bloque ignora separación de palabras cuando se usan caracteres con acentos  como mayusucula

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#297]
Tipo: Bug

Reproducible: Si

Forma de reproducirlo:
1. Abrir Gobstones Teacher
2. En la sección biblioteca del docente crear un procedimiento con el nombre
"IrAÚltimo"
3. Ir a la sección bloques y abrir la sección "Procedimientos Primitivos"

Comportamiento esperado:
El nombre del bloque figura como "Ir a último"

Comportamiento obtenido:
El nombre del bloque figura como "Ir aúltimo" (sin espacio entre a y último)

Comenarios:
El error ocurre con cualquier vocal con acento y con las palabras que comienzan con Ñ. Lo mismo ocurre con otros acentos que no son del español.

Debería tenerse en cuenta al menos las siguientes variantes para el español: Á, É, Í, Ó, Ú, Ñ

Si se desea soportar otros idiomas a futuro, sería útil soportar además otros diactríticos, como À, Ö, Å, Ç, entre otras. También puede que haya casos muy locos, como en el neerlandes, en donde la grafía ij se escribe en mayusculas como IJ, y no como Ij, por lo que una palabra que comienza con IJ debería leerse como una sola, y no como dos, solo en ese idioma.

**Comment by rodri042** [comment]
Duplicado de https://github.com/gobstones/gobstones-web/issues/324
