### ISSUE TITLE
Bloque "repetir hasta que" realiza chequeo de tipos

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#298]
Actualmente, como condición de un bloque "repetir hasta que" solo se puede poner un bloque que represente una expresión booleana, en lugar de cualquier bloque de expresión. Esto es inconsistente con el comportamiento de los demás bloques y además no permite colocar un bloque "completar" en el lugar de una condición.

**Comment by rodri042** [comment]
Esto quedó arreglado
