### ISSUE TITLE
Bloque "completar" desaparece junto a los bloques que le siguen

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#299]
Al reemplazar un bloque de comando "completar" por otro comando cualquiera, no desaparece solamente dicho bloque sino todos los que están enganchados debajo de él. Por ejemplo:
![imagen](https://user-images.githubusercontent.com/12092129/46100435-c1c9f880-c19f-11e8-8fa4-2d6a1317d50c.png)

Esto hace que el bloque "completar" solo se pueda usar al final de una secuencia de bloques, cuando uno podría querer indicar que es necesario agregar instrucciones en otro punto del programa.

**Comment by fidel-ml** [comment]
Este es un error que parece ser de Blockly. Es para chusmear, porque está feo...
