### ISSUE TITLE
El tooltip que indica errores en el código puede obstaculizar su corrección

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#312]
Al cometer un error en el código que produce BOOM, aparece un tooltip en el código indicando el bloque que produjo el error. A veces este tooltip puede estar encima de lo que es necesario corregir. Si bien se puede cerrar el tooltip haciendo clic en el símbolo de advertencia en el bloque, no es un comportamiento intutivo y me llevó un rato darme cuenta de eso. Quizás sería más cómodo que el tooltip tuviera un pequeño botón de cerrar.

Por ejemplo, en este caso, el error fue causado por una repetición ejecutándose una cantidad equivocada de veces, y el tooltip está tapando justamente el bloque de repetición.
![imagen](https://user-images.githubusercontent.com/12092129/47093177-06750c80-d1ff-11e8-9dbc-38cb73f7a230.png)

**Comment by alanrodas** [comment]
#282 propone que el modal se cierre si se modifica el código.
Tal vez sería interesante ambas opciones, el botón de cerrar, y el que se cierre automáticamente.
