### ISSUE TITLE
Al cambiar de curso en Desktop debería abrir un proyecto nuevo

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-web#314]

**Comment by fidel-ml** [comment]
Y si puedo agregar, refrescar el selector para que abra el primer capítulo.
Hoy muestra todo en blanco.

Adicionalmente, no hay ninguna referencia visual de en qué curso estoy. :(
FF

**Comment by rodri042** [comment]
Arreglado en https://github.com/gobstones/gobstones-web/commit/0be7dbc51657a1ec403599874a2598bda477224a
