### ISSUE TITLE
Hacer que la ejecución se detenga brevemente en el tablero inicial

### ISSUE THREAD

**Issue by francofrizzo** [gobstones/gobstones-web#320]
Al trabajar proyectos que tienen varios tableros iniciales distintos, si se ejecuta el programa repetidas veces, pueden verse los sucesivos tableros finales que se obtienen pero no los tableros iniciales a los que corresponden. Esto es especialmente confuso cuando se está utilizando la velocidad instantánea.

Una posible solución (a probar) sería que la ejecución se detenga una breve fracción de tiempo en el tablero inicial, independientemente de la velocidad de ejecución seleccionada.

**Comment by rodri042** [comment]
Hecho y subido a staging
