### ISSUE TITLE
Mejorar la UX de los errores de compilación

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#33]
Al apretar ejecutar no resulta obvio que el programa no hizo nada porque el programa no compila, no es suficiente con la cruz en la línea errónea.

Quizás se pueda mejorar poniendo un toast que indique que "hay errores".

**Comment by flbulgarelli** [comment]
@faloi recién probé y los errores de compilación no se muestran en el editor hasta que ejecutás. Eso está bien?

**Comment by faloi** [comment]
Sí, es el comportamiento que buscamos. De todos modos creo que el toast no
es suficiente, sería interesante además subrayar la línea errónea.
