### ISSUE TITLE
Getter de índice de foreach sin sincronizar

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#346]
El getter del índice de un foreach no está sincronizado con el bloque, como sí pasa con los parámetros. Dado que no es una variable, y que su alcance es exclusivamente dentro del foreach correspondiente, podría estar vinculado igualito que los parámetros (pero al bloque foreach).
O sea, cuando cambio el nombre del índice en el bloque, el getter no se altera (y sería coherente que lo hiciera...)

**Comment by rodri042** [comment]
(que los getters del foreach tengan un $parent)

**Comment by rodri042** [comment]
Va a estar disponible en el próximo build
