### ISSUE TITLE
Problemas con las vestimentas text en la versión Desktop

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#348]
Las vestimentas en formato texto en la versión 2.14.2 (la que se puede descargar actualmente), no se muestran. 

![image](https://user-images.githubusercontent.com/8825526/52226573-1f77fb00-288c-11e9-8edc-d939e210ed66.png)

**Comment by rodri042** [comment]
Tenés razón, me parece que esa versión la generé a mano porque no estaba andando el deploy automático (fue antes de que lo arreglara). Quizás lo armé con una versión vieja del tablero. En la actual está andando.

Si querés puedo subir a producción y que se arme una desktop nueva, pero te va a obligar a migrar los proyectos (`resto` -> `sinElPrimero`, `Asociaciones` -> `Eventos`, `defaults.yml` -> `meta-defaults.yml`), o me podés pasar los cursos y hago yo el rename

**Comment by fidel-ml** [comment]
No incorporemos staging antes de que yo logre hacer la migración... ¿Podrás
generarme una versión desktop de staging para usarla en mi máquina como
ambiente de desarrollo? (No para compartir, aún, hasta que no esté
todo...).
Mientras tanto, ¿se podrá corregir ese bug en la versión desktop actual, o
creés que no vale la pena?
Gracias.
FF

**Comment by rodri042** [comment]
Dale ahora la armo y te la mando por mail!

> Mientras tanto, ¿se podrá corregir ese bug en la versión desktop actual, o creés que no vale la pena?

Si podemos evitarlo, mejor. Generar una versión con versiones viejas de los componentes (blockly, intérprete, tablero, runner, etc.) es re manual y propenso a errores (ya con esta versión viste que puede ocurrir :stuck_out_tongue:)
