### ISSUE TITLE
La actividad "Descubrir la carta" no carga los bloques del toolbox en staging

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#349]
Ver https://gobstones.github.io/gobstones-jr-staging/?course=gobstones/curso-LPYSD2&github=gobstones/curso-LPYSD2&path=Unidades/1.Expresiones%20y%20funciones/3.Descubrir%20la%20carta

![image](https://user-images.githubusercontent.com/8825526/52227423-3ddef600-288e-11e9-8701-15e7ee323676.png)

**Comment by rodri042** [comment]
@fidel-ml el problema es que la biblioteca del docente no compila (al arrancar y cada vez que tocás play tira que la biblioteca del docente tiene errores).

No compila porque usa `resto` y eso ahora se llama `sinElPrimero`. Hay que migrar esos proyectos :)

**Comment by fidel-ml** [comment]
Como es en staging, la idea es que yo tengo que actualizar bocha de cosas
(unificando los extra y las vestimentas), por ejemplo, así que no te
preocupes. :D
Gracias.
FF
