### ISSUE TITLE
Versión 2.14.2 para Windows 10 64 bits no carga al abrir

### ISSUE THREAD

**Issue by hschinca** [gobstones/gobstones-web#351]
En mi Windows 10 Pro, descargué el instalador gobstones-jr-windows-2.14.2.exe, instalé Gobstones y lo quise abrir y se quedó "Cargando..." por siempre.

**Comment by alanrodas** [comment]
Confirmo mismo comportamiento tanto en Windows 32 bits y Linux. La versión está bugeada al trabajar offline.
