### ISSUE TITLE
El parámetro del foreach no acepta espacios

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#352]
Cuando se cambia el original `elemento` por `una carta` estalla al ejecutar.

Esto anda:
![seleccion_999 112](https://user-images.githubusercontent.com/5421992/53420997-98660080-39bb-11e9-8319-66bde8552ec3.png)

pero esto no:
![seleccion_999 113](https://user-images.githubusercontent.com/5421992/53421009-a0be3b80-39bb-11e9-855f-73b71b1b1338.png)

**Comment by rodri042** [comment]
Cierro por duplicado de https://github.com/gobstones/gobstones-web/issues/345

![screenshot1](https://user-images.githubusercontent.com/1631752/54566935-0ac17380-49b1-11e9-87a7-e96b7977f542.png)

Fue arreglado en staging. En la próxima subida a producción (@fidel-ml dirá cuándo) quedará!
