### ISSUE TITLE
Mientras se consigue versión estable marcar 2.14 como "draft" ?

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#354]
La 2.14 no anda y MUCHA gente que intenta descargársela se choca. ¿No podemos de alguna forma deshabilitar ese release en gobstones-web-desktop para que la última estable sea 2.12?

**Comment by fidel-ml** [comment]
Ya está disponible la versión 2.15 en la versión Desktop y en staging.
La online por el momento sigue siendo la anterior.
FF
