### ISSUE TITLE
Que no sea obligatorio crear la carpeta "content" al importar curso.

### ISSUE THREAD

**Issue by asanzo** [gobstones/gobstones-web#355]
Situación:

1. Estoy en una computadora _sin internet_.
1. Me bajé previamente en una carpeta el repo `https://github.com/gobstones/curso-lpysd2` (que es el que pienso distribuir en las máquinas sin internet).
1. Me meto en Gobstones JR desktop (Linux, AppImage de versión 2.12).
1. Click en el menú de cursos, botón `Importar curso`.

Problema:
**No puedo importar el curso que bajé previamente**. Ninguna carpeta es válida. Juli me tiró el tip de _renombrar la carpeta curso-lpysd2_ a una que se llame "content".

Lo deseado:
Me gustaría que al elegir cualquier carpeta que tenga el `guides.json` adentro pueda importarlo.

**Comment by rodri042** [comment]
Solucionado en 2.15.6
