### ISSUE TITLE
[BUG] [STAGING] [URGENTE] No se muestran los procedimientos primitivos en la lista

### ISSUE THREAD

**Issue by alanrodas** [gobstones/gobstones-web#357]
Contexto:
----------

* Abro Gobstones Sr en:
https://gobstones.github.io/gobstones-sr/?course=gobstones/curso-InPr-UNQ&github=gobstones/curso-InPr-UNQ&path=Proyectos/2.Procedimientos/4.La%20gran%20aventura%20del%20mar%20encantado
* Cierro la ventana de descripción y doy click en la lamparita amarilla donde debería ver los procedimientos primitivos.
* La lista de procedimientos primitivos se despliega en un popup en el centro de la pantalla.

Pasos para reproducir:
-----------------------
* Abro Gobstones Sr en Staging con el mismo ejercicio que antes:
https://gobstones.github.io/gobstones-sr-staging/?course=gobstones/curso-InPr-UNQ&github=gobstones/curso-InPr-UNQ&path=Proyectos/2.Procedimientos/4.La%20gran%20aventura%20del%20mar%20encantado
* Cierro la ventana de descripción y doy click en la lamparita amarilla donde debería ver los procedimientos primitivos.
* Se muestra el popup en el centro de la pantalla pero no hay procedimientos primitivos en ella.

Comentarios adicionales:
--------------------------
El bug debe haberse agregado con alguno de los últimos cambios, pues fuera de staging funciona bien.

**Comment by rodri042** [comment]
Fixeado
