### ISSUE TITLE
¿Se podrá lograr que cuando haya una versión nueva, el Desktop te avise de alguna forma?

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#366]
PilasBloques ahora lo hace... :D

**Comment by rodri042** [comment]
Puedo mostrar un cartel como 
![screenshot2](https://user-images.githubusercontent.com/1631752/57988493-931dcc80-7a65-11e9-97df-a482f422518b.png) y si acepta abrir un browser y mandarlo a https://github.com/gobstones/gobstones-web-desktop/releases/latest

¿Algo así va?

**Comment by fidel-ml** [comment]
Sí, totalmente.
FF

**Comment by rodri042** [comment]
Va a estar disponible en el próximo deploy
