### ISSUE TITLE
El tablero final queda feo despues de cambiarle el tamaño

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#37]
![image](https://cloud.githubusercontent.com/assets/1585835/17506114/a19c8114-5ddc-11e6-9ac7-a2dc3a09352c.png)

**Comment by rodri042** [comment]
Wooo.
No me sucede.
![screenshot4](https://cloud.githubusercontent.com/assets/1631752/17523016/6d55f44e-5e59-11e6-939d-b249838ce445.png)

Qué browser/versión usás?
Yo tengo Chrome 48.0.2564.116

**Comment by faloi** [comment]
Los pasos para reproducirlo son:

1. Ejecutá con el tablero que viene.
2. Cambiale el tamaño y volvé a ejecutar.

**Comment by rodri042** [comment]
Jaja qué simpático. Oka, ahí pude

**Comment by rodri042** [comment]
Fixed!
