### ISSUE TITLE
No se visualiza la vestimenta al cargar un project creado en GobstonesJr

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#397]
Creo el proyecto desde GobstonesTeacher, con una vestimenta, un tablero inicial, y configuro para que la vestimenta sea visible, y no se pueda eliminar (el selector de vestimentas no visible).
Salvo el .gbp desde GobstonesTeacher, y lo abro desde GobstonesJr. La vestimenta NO está habilitada.

**Comment by faloi** [comment]
Según vimos, lo que falta es el `visible: true` dentro de attire. Probablemente no le de bola al estado en que quedó en el editor.
