### ISSUE TITLE
Simplificar la pestaña de configuración

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#415]
# 🐞 Problema detectado

Me da la sensación de que la cantidad de opciones de configuración que hay actualmente puede resultar abrumadora para alguien que comienza a crear ejercicios. Por otro lado, pienso que hay opciones que _en general_ se activan o desactivan en bloque.

# :notebook: Acciones sugeridas

Una opción que se me ocurre para no perder flexibilidad y a la vez reducir el "espanto inicial" puede ser crear una especie de _presets_ o _configuraciones rápidas_ o algún nombre mejor que pueda surgir. En esencia serían simplemente una combinación de configuraciones que se establecen en bloque, y que luego un/a usuario/a con experiencia puede ajustar si lo necesita.

Las que se me ocurren ahora son:
* **Inicial con vestimenta**: oculta todo el panel de edición, solo se puede ejecutar el programa en el tablero inicial predefinido, con la vestimenta prendida.
* **Inicial sin vestimenta**: igual al anterior, pero sin vestimenta.
* **Avanzado**: se pueden utilizar todas las opciones.

En su versión más simple, me imagino tener un botón por configuración rápida, arriba de lo que hay ahora. Si queremos apostar un poco más a esta idea, podemos hacer algo más vistoso, que explique un poco qué incluye cada configuración. Y luego poner un botón o algo que permita pasar a la sección de _configuración avanzada_.

# ☝🏽 Dependencias
#419

**Comment by faloi** [comment]
@fidel-ml leete esto, si querés lo discutimos mañana. Obviamente los nombres y las combinaciones propuestas están sujetas a discusión, pero yo creo que puede ser una mejora interesante.

**Comment by fidel-ml** [comment]
"Actividad cerrada con dominio": contenido de tablero no editable, tableros iniciales aleatorios, vestimenta visible no editable, velocidad ajustable iniciada en velocidad rápida

"Actividad cerrada sin dominio":  ídem, pero con vestimenta no visible no editable

"Actividad de representación con dominio": ídem, pero con vestimenta visible editable

"Actividad cerrada senior":  contenido de tablero no editable, elegir tablero inicial, vestimenta no visible no editable, velocidad ajustable en instantáneo

**Comment by alanrodas** [comment]
Me parece que hay por lo menos dos niveles de presets. Uno que está relacionado al tablero de la aplicación, donde yo veo 4 casos:
* **Con vestimenta fija** (Donde hay una vestimenta y no se cambia)
* **Con vestimenta desactibable** (Donde esté habilitado el toggle de vestimentas, pero arranque con la misma)
* **Con vestimenta invisible** (Donde hay vestimenta pero se arranca con la misma invisible)
* **Sin vestimentas** (Donde no hay vestimentas)

Luego me parece que podríamos pensar presets para los bloques. Algo como:
* **Todos los bloques disponibles**
* **Con bloques hasta "repetición condicional"**
* **Con bloques hasta "alternativa condicional"**
* **Con bloques hasta "Repetición simple"**
* o algo similar.

O sea, que puedan configurar rápidamente los bloques disponibles según un punto en la propuesta pedagógica.

**Comment by fidel-ml** [comment]
Lo de los presets para bloques me gusta, pero habría que pensarlos bien en base a la didáctica propuesta por nosotros. :)

**Comment by fidel-ml** [comment]
¿Fede, estás pensando en que el tab de configuración tenga una versión "simple" y una "avanzada"? O sea, ¿que en la "simple" solamente se vean los presets, y que si pide avanzada vea todo, o que esté todo pero al tope de cada una esté el preset?

**Comment by alanrodas** [comment]
Si hace algo como lo que yo propongo, veo un dropdown en cada "grupo" de elementos, en donde el dropdown tiene presents y una opción "Configuración personalizada" para poder colocar tus opciones en cada parte.
Entonces uno tiene 2/3 combos y elige entre esos opciones simples, o, puede expandir en cualquiera de ellos si se necesita (aunque sin enroscarse en los otros).

**Comment by faloi** [comment]
La verdad que yo pensaba algo mucho más simple, basándome en lo que recuerdo de cuando yo participé del curso B (nuestro público objetivo).

Sí coincido con Alan en que la configuración de tablero es independiente de la de los bloques disponibles. La propuesta de "hasta X concepto" puede andar, pensando en la secuencia didáctica Gobstones, pero habría que ver si con tanta granularidad no terminamos replicando el árbol que ya está.

**Comment by faloi** [comment]
### Bloques

- [ ] Con dominio: excluye Comandos primitivos, Expresiones primitivas.

* **Inicial:** Poner, Mover, Sacar, procedimientos simples, expresiones literales (color y dirección).
* **Medio:** procedimientos con parámetros, expresiones numéricas, expresiones booleanas, repetición simple, alternativa condicional, funciones simples.
* **Avanzado:** funciones con procesamiento, repetición condicional. 
* **Libre:** todo.

Procedimientos primitivos y funciones primitivas, en todas.

### Visualización

* **Actividad junior con dominio:** contenido de tablero no editable, tableros iniciales aleatorios, vestimenta visible no editable, velocidad ajustable iniciada en velocidad rápida.
* **Actividad junior sin dominio:** ídem, pero con vestimenta no visible no editable.
* **Actividad de representación con dominio:** ídem, pero con vestimenta visible editable.
* **Actividad senior:** contenido de tablero no editable, elegir tablero inicial, vestimenta no visible no editable, velocidad ajustable en instantáneo.
