### ISSUE TITLE
Chequeos de tipo en comandos primitivos: Mover, Poner, IrAlBorde

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gobstones-web#42]
Cuando algún comando primitivo recibe un argumento de tipo incorrecto, debería informarse con un mensaje del estilo `Problema de tipos: el comando Poner esperaba una dirección pero se obtuvo Rojo`.

**Comment by gobstones-admin** [comment]
Es correcto que produzca boom...
Gobstones no utiliza un sistema de tipos estático para validar sus
programas, y consecuentemente, los errores de tipo son dinámicos (boom).
Sí existe un sistema de tipos estático con el que se puede detectar ese
error, pero es incorrecto utilizarlo antes de la corrida del programa. Esa
es la función del botón "Chequear" en PyGobstones (que estaría bueno que
estuviese, aunque no es primordial).
FF

2016-08-12 1:36 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by fidel-ml** [comment]
El problema de este error es que dice "Te caíste del tablero por x=0, y=0", en lugar de decir "Problema de tipos: Rojo no es una dirección".
Un error similar debería dar el comando Poner cuando recibe una dirección (o cualquier valor de tipo no numérico), pero en este momento no hace nada (ni siquiera las instrucciones anteriores o posteriores).

¿Se hacen chequeos de tipo durante la ejecución? No deben hacerlo solamente los comandos Poner y Mover, sino todo aquel procedimiento que reciba parámetros (al menos la cantidad, ya que no se verifica el tipo de un dato hasta que se lo usa en un comando primitivo).

Y para las variables, el chequeo de tipos es uno de consistencia: todas las operaciones tienen que ser consistentes con el tipo del dato usado en la primera asignación.
