### ISSUE TITLE
Un programa que utiliza una primitiva o procedimiento no reconocido no debería ejecutar

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gobstones-web#43]
El siguiente programa no arroja errores de compilación, pero ejecuta y produce un resultado distinto de `BOOM`.

```
program { 
    Poner(Rojo) 
    Movr(Rojo)
    Poner(Rojo)    
}
```

Es extraño porque estoy casi seguro de haber visto hace una semana las validaciones en tiempo de compilación funcionando.

**Comment by gobstones-admin** [comment]
¡¡¡Atención con qué validaciones hacen en tiempo de compilación!!!
Ese programa debería dar error (estático) porque el procedimiento Movr no
está definido...
FF

2016-08-12 1:42 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:
