### ISSUE TITLE
No se pueden agregar o sacar tableros en el modo libre

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#439]
Eso: nunca aparecen las opciones de vaciar tablero, agregar tablero o borrar tablero.
Si un docente quiere agregar o sacar tableros, no se puede :( (Agregar puede usar "Cargar" desde afuera, pero no se pueden borrar ni  vaciar de una).
También sería deseable que en el modo libre esto aparezca en la visualización del estudiante...

**Comment by faloi** [comment]
Bueno, no lo logro reproducir...

![modo-libre](https://user-images.githubusercontent.com/1585835/143625450-c07621da-7365-42ba-8f34-cc006472c8b2.gif)

¿@fidel-ml alguna idea?
