### ISSUE TITLE
No funciona correctamente el scroll en biblioteca docente

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#444]
Las últimas líneas del editor de texto de la biblioteca del docente no se ven.
Si te posicionás al final (sin ver) y agregás líneas, lo muestra, pero desplaza toda la ventana hacia arriba y no se puede volver (y si no salvaste, chau, fuiste... :().

**Comment by faloi** [comment]
Moví la parte de vestimentas a #458, porque no está relacionada con esta.
