### ISSUE TITLE
Importar/exportar tableros en la UI usando el GbbWriter y GbbBuilder de gs-weblang-core

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-web#60]
Para mantener la compatibilidad con los ejercicios existentes, esto tiene que poder hacerse desde el intérprete y desde la UI.

Fíjense dónde conviene meter la lógica para hacer el parseo, pero se va a necesitar en ambos lados.

**Comment by faloi** [comment]
Acá tienen el parser que usa hoy Mumuki, hecho en Ruby: https://github.com/uqbar-project/ruby-stones/blob/master/lib/stones/gbb/gbb_reader.rb.

**Comment by faloi** [comment]
Se tiene que poder guardar también el tablero final.

**Comment by rodri042** [comment]
Creo que lo mejor es que esta lógica esté del lado del intérprete, no? Y
que genere un `table` parecido a lo que devuelve ahora al parsear

2016-08-30 16:19 GMT-03:00 Federico Aloi <notifications@github.com>:
