### ISSUE TITLE
¿Comodidades en la edición del tablero inicial?

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#72]
Estaría copado contar con un par de comodidades a la hora de editar el tablero inicial:
1.- un botón para vaciar el tablero (con confirmación o bien undo...).
2.- que haya modificadores para agregar o sacar bolitas de a 10 (por ejemplo, ALT-CLICK)
3.- que haya un help fácil de acceder para saber cómo editar (eg. CTRL-CLICK mueve el cabezal... ;) Aunque estaría mejor que las flechas moviesen al cabezal... o flecha-CLICK?)
4.- que se pueda hacer CTRL-C sobre una celda y CTRL-V sobre otra para pegar la copiada... :dagger: 

FF

**Comment by rodri042** [comment]
La 1 y 2 están implementadas, las otras las charlamos y cuando definamos mejor hacemos otro issue aparte
