### ISSUE TITLE
Mejorar visualización de celdas con muchas bolitas

### ISSUE THREAD

**Issue by fidel-ml** [gobstones/gobstones-web#77]
Sería importante que en una celda pueda ir realmente cualquier número de bolitas. Para esto, una idea posible es que cuando el número a colocar se muy largo, se lo reemplace por un * y que al pasar con el mouse sobre la bolita, una ventana emergente indique el número.
Esto no es solamente para el editor, pero aprovecho la volada. :D

**Comment by rodri042** [comment]
Hecho en https://github.com/gobstones/gs-board/commit/219429269d7caa65786ea0b4413d03e3ce269ef9
